### ISSUE TITLE
Documentation or examples?

### ISSUE THREAD

**Issue by adundovi** [kit-ty-kate/ocamldap#3]
Hi, is there any doc or examples how to use this library?

**Comment by kit-ty-kate** [comment]
I'm not the original author of the library and I have no idea how to use it thb, I'm just trying to maintain it the best I can.

Though you can see the tests here: https://github.com/kit-ty-kate/ocamldap/tree/master/tests
and also maybe this example from the ocsigen project which I help maintained: https://github.com/ocsigen/ocsimore/blob/cfbf0d8140f52908ee1e61aac897adcd1c81a868/src/user/ldap/ocsimore_ldap.ml

**Comment by adundovi** [comment]
Ok, I understand the situation. If I will learn how to use it, I can write a few lines and make a PR. Thanks for the second link, nevertheless :-)
