### ISSUE TITLE
Suspicious literal ? 

### ISSUE THREAD

**Issue by hhugo** [kit-ty-kate/ocamldap#4]
The following line only contains seven 1s in the last group. Is this expected ?

https://github.com/kit-ty-kate/ocamldap/blob/753546d48e389cad38e67498a9bef752d37dcf45/src/ldap/lber.ml#L530

**Comment by kit-ty-kate** [comment]
I have no idea. I'm not the original author of this library. If you understand more than me or want to get the ownership of the library you're welcome to do so ^^"
